### ISSUE TITLE
Pre-Compiled JARs

### ISSUE THREAD

**Issue by 2827471** [timing1337/Mineplex#16]
Any chance you could provide the already compiled versions of the modified plugins?

**Comment by GX2H912** [comment]
It's very easy to do on your own.
Simply clone the repository, import into intellij, delete the non-modified source and keep the modified one, fix a few of the pom files and resolve dependencies (like spigot in README and installing patches, etc), run all the checks in maven (including compiling), and import the Hub.jar and Arcade.jar into their respective plugin folders. 

Also import Mineplexer.jar and BungeeCordRotator.jar into your BungeeCord server.

Then configure the server-configuration files, the plugin.ymls for all the servers and you should be set. (don't forget mysql, redis, and web-server which are especially important in getting yours running)

**Comment by petethepossum** [comment]
The YouTube tutorial linked in the readme is useful in helping with the redis and sql setup, also if you look hard enough on GitHub there are some bash scripts to make redis keys for you :)
