### ISSUE TITLE
sql dump fix please

### ISSUE THREAD

**Issue by LeePC** [timing1337/Mineplex#18]
An error occurs because it is not properly registered

**Comment by timing1337** [comment]
Any details?

**Comment by LeePC** [comment]
An error occurs in npc manager
I checked and it seems that the sql part was not properly registered

**Comment by timing1337** [comment]
Nope its a problem related to your mysql server

```
Client does not support authentication protocol requested by server; consider upgrading MySQL client
```

I'm not an expert in MySQL so i don't really know whats wrong though

**Comment by LeePC** [comment]
MYSQL Workbench has already been installed

**Comment by LeePC** [comment]
I'm sorry. I solved it Thank you for your answer
