### ISSUE TITLE
How should I give the rank??

### ISSUE THREAD

**Issue by LeePC** [timing1337/Mineplex#21]
Can you tell me how to give it to me??

**Comment by petethepossum** [comment]
Use /rank set (ign) (rank) 

To see ranks available do /rank list

Also helps to OP yourself in the console

**Comment by petethepossum** [comment]
Also for general questions it's usually best practice not to open an issue on the source code itself as there is no issue on display here

**Comment by Aduhkiss** [comment]
Another method would be to just change it manually in the MySQL database

**Comment by petethepossum** [comment]
> Another method would be to just change it manually in the MySQL database

@LeePC there are instructions on how to do this in the linked YouTube in the Readme

**Comment by LeePC** [comment]
Thank you for the explanation.

**Comment by timing1337** [comment]
Resolved
