### ISSUE TITLE
Null pointer error on the attempted creation of NPC

### ISSUE THREAD

**Issue by petethepossum** [timing1337/Mineplex#22]
On the creation of an NPC a null pointer error occurs, even though the NPC data gets added to the DB, this later causes another error on the startup of Hub, that is remedied by deleting the unused NPC data from the npc table

**Comment by petethepossum** [comment]
Will attach more info later / a log

**Comment by GX2H912** [comment]
Yeah your newnpcs and/or npcs tables are messed up

**Comment by GX2H912** [comment]
https://github.com/timing1337/Mineplex/commit/dec661dc484eed5dac7efc1f45f40b017e1f20a3

See if this works

**Comment by petethepossum** [comment]
Perfect, thank you will take a look later. Had set the default to Null in some tables forgot about NPCs

**Comment by GX2H912** [comment]
(Sorry that was a separate thing that I was meaning to push that may have helped). I also pushed the actual fix here (by adding Tron to WorldConfig here) https://github.com/timing1337/Mineplex/commit/a8954a6f4f903313391f19ec925a1d5d64c01c7d

**Comment by timing1337** [comment]
Fixed #24
