### ISSUE TITLE
Disguise Command Issue - profileCacheRepo does not store "_propertyMap" value

### ISSUE THREAD

**Issue by GX2H912** [timing1337/Mineplex#26]
(A side note for disguises is that the "modifiers" bug in UtilGameProfile is only present in versions of Java 12+, so I used Java 11 instead)

The issue lies in the ProfileCacheManager.java file. The  _propertyMap value in the redis isn't generated:

Here is an example:

When executing /disguise nuts,
A key called "data.profileCacheRepo.ALL.nuts" is created with the following contents:

{
  "_uuid": "4162183a-6d6f-4c3f-a7cc-7cf9f996566b",
  "_playerName": "nuts",
  "_propertyMap": "[]"
}

Nothing else happens after that point. No console logging, no errors, nothing.

Note that "_propertyMap" is null because none is fetched in the following code in ProfileCacheManager.java:

```/**
	 * Tries to get a GameProfile; guaranteed to be an unique instance
	 */
	public GameProfile attemptToLoadProfile(String playerName)
	{
		ProfileData profile = _profileRepository.getElement(playerName.toLowerCase());
		if (profile != null)
		{
			PropertyMap propertyMap = _gson.fromJson(profile.getPropertyMap(), PropertyMap.class);
			GameProfile gameProfile = new GameProfile(profile.getUuid(), profile.getPlayerName());
			gameProfile.getProperties().putAll(propertyMap);
			return gameProfile;
		}
		return null;
	}
```

"propertyMap" returns {}, and nothing happens. Even if there is data for propertyMap, I don't exactly think that it registers this anyways. We need some sort of a fix for this to fix disguise.

The main issue is this snippet of code: `gameProfile.getProperties().putAll(propertyMap);` (since nothing returns after that point even if propertyMap were to be specified)

I am not exactly sure whether this is a spigot and guava conflict either.

**Comment by timing1337** [comment]
Fixed https://github.com/timing1337/Mineplex/commit/5232b3ef9ef53d93cba279778368cd81f453c96f

**Comment by GX2H912** [comment]
ProfileCache has worked fine, profileCacheRepo just doesn't.
